# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: alexa.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import response_status_pb2 as response__status__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0b\x61lexa.proto\x12\x1e\x41nki.Vector.external_interface\x1a\x15response_status.proto\"\x17\n\x15\x41lexaAuthStateRequest\"\xab\x01\n\x16\x41lexaAuthStateResponse\x12>\n\x06status\x18\x01 \x01(\x0b\x32..Anki.Vector.external_interface.ResponseStatus\x12\x42\n\nauth_state\x18\x02 \x01(\x0e\x32..Anki.Vector.external_interface.AlexaAuthState\x12\r\n\x05\x65xtra\x18\x03 \x01(\t\"#\n\x11\x41lexaOptInRequest\x12\x0e\n\x06opt_in\x18\x01 \x01(\x08\"T\n\x12\x41lexaOptInResponse\x12>\n\x06status\x18\x01 \x01(\x0b\x32..Anki.Vector.external_interface.ResponseStatus\"c\n\x0e\x41lexaAuthEvent\x12\x42\n\nauth_state\x18\x01 \x01(\x0e\x32..Anki.Vector.external_interface.AlexaAuthState\x12\r\n\x05\x65xtra\x18\x02 \x01(\t*\xa2\x01\n\x0e\x41lexaAuthState\x12\x16\n\x12\x41LEXA_AUTH_INVALID\x10\x00\x12\x1c\n\x18\x41LEXA_AUTH_UNINITIALIZED\x10\x01\x12\x1e\n\x1a\x41LEXA_AUTH_REQUESTING_AUTH\x10\x02\x12\x1f\n\x1b\x41LEXA_AUTH_WAITING_FOR_CODE\x10\x03\x12\x19\n\x15\x41LEXA_AUTH_AUTHORIZED\x10\x04\x62\x06proto3')

_ALEXAAUTHSTATE = DESCRIPTOR.enum_types_by_name['AlexaAuthState']
AlexaAuthState = enum_type_wrapper.EnumTypeWrapper(_ALEXAAUTHSTATE)
ALEXA_AUTH_INVALID = 0
ALEXA_AUTH_UNINITIALIZED = 1
ALEXA_AUTH_REQUESTING_AUTH = 2
ALEXA_AUTH_WAITING_FOR_CODE = 3
ALEXA_AUTH_AUTHORIZED = 4


_ALEXAAUTHSTATEREQUEST = DESCRIPTOR.message_types_by_name['AlexaAuthStateRequest']
_ALEXAAUTHSTATERESPONSE = DESCRIPTOR.message_types_by_name['AlexaAuthStateResponse']
_ALEXAOPTINREQUEST = DESCRIPTOR.message_types_by_name['AlexaOptInRequest']
_ALEXAOPTINRESPONSE = DESCRIPTOR.message_types_by_name['AlexaOptInResponse']
_ALEXAAUTHEVENT = DESCRIPTOR.message_types_by_name['AlexaAuthEvent']
AlexaAuthStateRequest = _reflection.GeneratedProtocolMessageType('AlexaAuthStateRequest', (_message.Message,), {
  'DESCRIPTOR' : _ALEXAAUTHSTATEREQUEST,
  '__module__' : 'alexa_pb2'
  # @@protoc_insertion_point(class_scope:Anki.Vector.external_interface.AlexaAuthStateRequest)
  })
_sym_db.RegisterMessage(AlexaAuthStateRequest)

AlexaAuthStateResponse = _reflection.GeneratedProtocolMessageType('AlexaAuthStateResponse', (_message.Message,), {
  'DESCRIPTOR' : _ALEXAAUTHSTATERESPONSE,
  '__module__' : 'alexa_pb2'
  # @@protoc_insertion_point(class_scope:Anki.Vector.external_interface.AlexaAuthStateResponse)
  })
_sym_db.RegisterMessage(AlexaAuthStateResponse)

AlexaOptInRequest = _reflection.GeneratedProtocolMessageType('AlexaOptInRequest', (_message.Message,), {
  'DESCRIPTOR' : _ALEXAOPTINREQUEST,
  '__module__' : 'alexa_pb2'
  # @@protoc_insertion_point(class_scope:Anki.Vector.external_interface.AlexaOptInRequest)
  })
_sym_db.RegisterMessage(AlexaOptInRequest)

AlexaOptInResponse = _reflection.GeneratedProtocolMessageType('AlexaOptInResponse', (_message.Message,), {
  'DESCRIPTOR' : _ALEXAOPTINRESPONSE,
  '__module__' : 'alexa_pb2'
  # @@protoc_insertion_point(class_scope:Anki.Vector.external_interface.AlexaOptInResponse)
  })
_sym_db.RegisterMessage(AlexaOptInResponse)

AlexaAuthEvent = _reflection.GeneratedProtocolMessageType('AlexaAuthEvent', (_message.Message,), {
  'DESCRIPTOR' : _ALEXAAUTHEVENT,
  '__module__' : 'alexa_pb2'
  # @@protoc_insertion_point(class_scope:Anki.Vector.external_interface.AlexaAuthEvent)
  })
_sym_db.RegisterMessage(AlexaAuthEvent)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _ALEXAAUTHSTATE._serialized_start=494
  _ALEXAAUTHSTATE._serialized_end=656
  _ALEXAAUTHSTATEREQUEST._serialized_start=70
  _ALEXAAUTHSTATEREQUEST._serialized_end=93
  _ALEXAAUTHSTATERESPONSE._serialized_start=96
  _ALEXAAUTHSTATERESPONSE._serialized_end=267
  _ALEXAOPTINREQUEST._serialized_start=269
  _ALEXAOPTINREQUEST._serialized_end=304
  _ALEXAOPTINRESPONSE._serialized_start=306
  _ALEXAOPTINRESPONSE._serialized_end=390
  _ALEXAAUTHEVENT._serialized_start=392
  _ALEXAAUTHEVENT._serialized_end=491
# @@protoc_insertion_point(module_scope)
