# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: behavior.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import messages_pb2 as messages__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0e\x62\x65havior.proto\x12\x1e\x41nki.Vector.external_interface\x1a\x0emessages.proto\"\x10\n\x0e\x43ontrolRelease\"\xae\x01\n\x0e\x43ontrolRequest\x12I\n\x08priority\x18\x01 \x01(\x0e\x32\x37.Anki.Vector.external_interface.ControlRequest.Priority\"Q\n\x08Priority\x12\x0b\n\x07UNKNOWN\x10\x00\x12\x16\n\x12OVERRIDE_BEHAVIORS\x10\n\x12\x0b\n\x07\x44\x45\x46\x41ULT\x10\x14\x12\x13\n\x0fRESERVE_CONTROL\x10\x1e\"\xbe\x01\n\x16\x42\x65haviorControlRequest\x12I\n\x0f\x63ontrol_release\x18\x01 \x01(\x0b\x32..Anki.Vector.external_interface.ControlReleaseH\x00\x12I\n\x0f\x63ontrol_request\x18\x02 \x01(\x0b\x32..Anki.Vector.external_interface.ControlRequestH\x00\x42\x0e\n\x0crequest_type\"\x18\n\x16\x43ontrolGrantedResponse\"\x15\n\x13\x43ontrolLostResponse\"\x1d\n\x1bReservedControlLostResponse\"\x82\x03\n\x17\x42\x65haviorControlResponse\x12Z\n\x18\x63ontrol_granted_response\x18\x01 \x01(\x0b\x32\x36.Anki.Vector.external_interface.ControlGrantedResponseH\x00\x12Q\n\x12\x63ontrol_lost_event\x18\x02 \x01(\x0b\x32\x33.Anki.Vector.external_interface.ControlLostResponseH\x00\x12\x43\n\nkeep_alive\x18\x03 \x01(\x0b\x32-.Anki.Vector.external_interface.KeepAlivePingH\x00\x12\x62\n\x1breserved_control_lost_event\x18\x04 \x01(\x0b\x32;.Anki.Vector.external_interface.ReservedControlLostResponseH\x00\x42\x0f\n\rresponse_typeb\x06proto3')



_CONTROLRELEASE = DESCRIPTOR.message_types_by_name['ControlRelease']
_CONTROLREQUEST = DESCRIPTOR.message_types_by_name['ControlRequest']
_BEHAVIORCONTROLREQUEST = DESCRIPTOR.message_types_by_name['BehaviorControlRequest']
_CONTROLGRANTEDRESPONSE = DESCRIPTOR.message_types_by_name['ControlGrantedResponse']
_CONTROLLOSTRESPONSE = DESCRIPTOR.message_types_by_name['ControlLostResponse']
_RESERVEDCONTROLLOSTRESPONSE = DESCRIPTOR.message_types_by_name['ReservedControlLostResponse']
_BEHAVIORCONTROLRESPONSE = DESCRIPTOR.message_types_by_name['BehaviorControlResponse']
_CONTROLREQUEST_PRIORITY = _CONTROLREQUEST.enum_types_by_name['Priority']
ControlRelease = _reflection.GeneratedProtocolMessageType('ControlRelease', (_message.Message,), {
  'DESCRIPTOR' : _CONTROLRELEASE,
  '__module__' : 'behavior_pb2'
  # @@protoc_insertion_point(class_scope:Anki.Vector.external_interface.ControlRelease)
  })
_sym_db.RegisterMessage(ControlRelease)

ControlRequest = _reflection.GeneratedProtocolMessageType('ControlRequest', (_message.Message,), {
  'DESCRIPTOR' : _CONTROLREQUEST,
  '__module__' : 'behavior_pb2'
  # @@protoc_insertion_point(class_scope:Anki.Vector.external_interface.ControlRequest)
  })
_sym_db.RegisterMessage(ControlRequest)

BehaviorControlRequest = _reflection.GeneratedProtocolMessageType('BehaviorControlRequest', (_message.Message,), {
  'DESCRIPTOR' : _BEHAVIORCONTROLREQUEST,
  '__module__' : 'behavior_pb2'
  # @@protoc_insertion_point(class_scope:Anki.Vector.external_interface.BehaviorControlRequest)
  })
_sym_db.RegisterMessage(BehaviorControlRequest)

ControlGrantedResponse = _reflection.GeneratedProtocolMessageType('ControlGrantedResponse', (_message.Message,), {
  'DESCRIPTOR' : _CONTROLGRANTEDRESPONSE,
  '__module__' : 'behavior_pb2'
  # @@protoc_insertion_point(class_scope:Anki.Vector.external_interface.ControlGrantedResponse)
  })
_sym_db.RegisterMessage(ControlGrantedResponse)

ControlLostResponse = _reflection.GeneratedProtocolMessageType('ControlLostResponse', (_message.Message,), {
  'DESCRIPTOR' : _CONTROLLOSTRESPONSE,
  '__module__' : 'behavior_pb2'
  # @@protoc_insertion_point(class_scope:Anki.Vector.external_interface.ControlLostResponse)
  })
_sym_db.RegisterMessage(ControlLostResponse)

ReservedControlLostResponse = _reflection.GeneratedProtocolMessageType('ReservedControlLostResponse', (_message.Message,), {
  'DESCRIPTOR' : _RESERVEDCONTROLLOSTRESPONSE,
  '__module__' : 'behavior_pb2'
  # @@protoc_insertion_point(class_scope:Anki.Vector.external_interface.ReservedControlLostResponse)
  })
_sym_db.RegisterMessage(ReservedControlLostResponse)

BehaviorControlResponse = _reflection.GeneratedProtocolMessageType('BehaviorControlResponse', (_message.Message,), {
  'DESCRIPTOR' : _BEHAVIORCONTROLRESPONSE,
  '__module__' : 'behavior_pb2'
  # @@protoc_insertion_point(class_scope:Anki.Vector.external_interface.BehaviorControlResponse)
  })
_sym_db.RegisterMessage(BehaviorControlResponse)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _CONTROLRELEASE._serialized_start=66
  _CONTROLRELEASE._serialized_end=82
  _CONTROLREQUEST._serialized_start=85
  _CONTROLREQUEST._serialized_end=259
  _CONTROLREQUEST_PRIORITY._serialized_start=178
  _CONTROLREQUEST_PRIORITY._serialized_end=259
  _BEHAVIORCONTROLREQUEST._serialized_start=262
  _BEHAVIORCONTROLREQUEST._serialized_end=452
  _CONTROLGRANTEDRESPONSE._serialized_start=454
  _CONTROLGRANTEDRESPONSE._serialized_end=478
  _CONTROLLOSTRESPONSE._serialized_start=480
  _CONTROLLOSTRESPONSE._serialized_end=501
  _RESERVEDCONTROLLOSTRESPONSE._serialized_start=503
  _RESERVEDCONTROLLOSTRESPONSE._serialized_end=532
  _BEHAVIORCONTROLRESPONSE._serialized_start=535
  _BEHAVIORCONTROLRESPONSE._serialized_end=921
# @@protoc_insertion_point(module_scope)
