# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: nav_map.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rnav_map.proto\x12\x1e\x41nki.Vector.external_interface\"x\n\x0eNavMapQuadInfo\x12\x43\n\x07\x63ontent\x18\x01 \x01(\x0e\x32\x32.Anki.Vector.external_interface.NavNodeContentType\x12\r\n\x05\x64\x65pth\x18\x02 \x01(\r\x12\x12\n\ncolor_rgba\x18\x03 \x01(\r\"{\n\nNavMapInfo\x12\x12\n\nroot_depth\x18\x01 \x01(\x05\x12\x14\n\x0croot_size_mm\x18\x02 \x01(\x02\x12\x15\n\rroot_center_x\x18\x03 \x01(\x02\x12\x15\n\rroot_center_y\x18\x04 \x01(\x02\x12\x15\n\rroot_center_z\x18\x05 \x01(\x02\"&\n\x11NavMapFeedRequest\x12\x11\n\tfrequency\x18\x01 \x01(\x02\"\xa9\x01\n\x12NavMapFeedResponse\x12\x11\n\torigin_id\x18\x01 \x01(\r\x12<\n\x08map_info\x18\x02 \x01(\x0b\x32*.Anki.Vector.external_interface.NavMapInfo\x12\x42\n\nquad_infos\x18\x03 \x03(\x0b\x32..Anki.Vector.external_interface.NavMapQuadInfo*\xc8\x02\n\x12NavNodeContentType\x12\x14\n\x10NAV_NODE_UNKNOWN\x10\x00\x12\x1e\n\x1aNAV_NODE_CLEAR_OF_OBSTACLE\x10\x01\x12\x1b\n\x17NAV_NODE_CLEAR_OF_CLIFF\x10\x02\x12\x1a\n\x16NAV_NODE_OBSTACLE_CUBE\x10\x03\x12\x1f\n\x1bNAV_NODE_OBSTACLE_PROXIMITY\x10\x04\x12(\n$NAV_NODE_OBSTACLE_PROXIMITY_EXPLORED\x10\x05\x12\"\n\x1eNAV_NODE_OBSTACLE_UNRECOGNIZED\x10\x06\x12\x12\n\x0eNAV_NODE_CLIFF\x10\x07\x12\x1d\n\x19NAV_NODE_INTERESTING_EDGE\x10\x08\x12!\n\x1dNAV_NODE_NON_INTERESTING_EDGE\x10\tb\x06proto3')

_NAVNODECONTENTTYPE = DESCRIPTOR.enum_types_by_name['NavNodeContentType']
NavNodeContentType = enum_type_wrapper.EnumTypeWrapper(_NAVNODECONTENTTYPE)
NAV_NODE_UNKNOWN = 0
NAV_NODE_CLEAR_OF_OBSTACLE = 1
NAV_NODE_CLEAR_OF_CLIFF = 2
NAV_NODE_OBSTACLE_CUBE = 3
NAV_NODE_OBSTACLE_PROXIMITY = 4
NAV_NODE_OBSTACLE_PROXIMITY_EXPLORED = 5
NAV_NODE_OBSTACLE_UNRECOGNIZED = 6
NAV_NODE_CLIFF = 7
NAV_NODE_INTERESTING_EDGE = 8
NAV_NODE_NON_INTERESTING_EDGE = 9


_NAVMAPQUADINFO = DESCRIPTOR.message_types_by_name['NavMapQuadInfo']
_NAVMAPINFO = DESCRIPTOR.message_types_by_name['NavMapInfo']
_NAVMAPFEEDREQUEST = DESCRIPTOR.message_types_by_name['NavMapFeedRequest']
_NAVMAPFEEDRESPONSE = DESCRIPTOR.message_types_by_name['NavMapFeedResponse']
NavMapQuadInfo = _reflection.GeneratedProtocolMessageType('NavMapQuadInfo', (_message.Message,), {
  'DESCRIPTOR' : _NAVMAPQUADINFO,
  '__module__' : 'nav_map_pb2'
  # @@protoc_insertion_point(class_scope:Anki.Vector.external_interface.NavMapQuadInfo)
  })
_sym_db.RegisterMessage(NavMapQuadInfo)

NavMapInfo = _reflection.GeneratedProtocolMessageType('NavMapInfo', (_message.Message,), {
  'DESCRIPTOR' : _NAVMAPINFO,
  '__module__' : 'nav_map_pb2'
  # @@protoc_insertion_point(class_scope:Anki.Vector.external_interface.NavMapInfo)
  })
_sym_db.RegisterMessage(NavMapInfo)

NavMapFeedRequest = _reflection.GeneratedProtocolMessageType('NavMapFeedRequest', (_message.Message,), {
  'DESCRIPTOR' : _NAVMAPFEEDREQUEST,
  '__module__' : 'nav_map_pb2'
  # @@protoc_insertion_point(class_scope:Anki.Vector.external_interface.NavMapFeedRequest)
  })
_sym_db.RegisterMessage(NavMapFeedRequest)

NavMapFeedResponse = _reflection.GeneratedProtocolMessageType('NavMapFeedResponse', (_message.Message,), {
  'DESCRIPTOR' : _NAVMAPFEEDRESPONSE,
  '__module__' : 'nav_map_pb2'
  # @@protoc_insertion_point(class_scope:Anki.Vector.external_interface.NavMapFeedResponse)
  })
_sym_db.RegisterMessage(NavMapFeedResponse)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _NAVNODECONTENTTYPE._serialized_start=509
  _NAVNODECONTENTTYPE._serialized_end=837
  _NAVMAPQUADINFO._serialized_start=49
  _NAVMAPQUADINFO._serialized_end=169
  _NAVMAPINFO._serialized_start=171
  _NAVMAPINFO._serialized_end=294
  _NAVMAPFEEDREQUEST._serialized_start=296
  _NAVMAPFEEDREQUEST._serialized_end=334
  _NAVMAPFEEDRESPONSE._serialized_start=337
  _NAVMAPFEEDRESPONSE._serialized_end=506
# @@protoc_insertion_point(module_scope)
