name: Release

on:
  release:
    types: [published]

jobs:
  release_zip_file:
    name: Prepare release asset
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Get version
        id: version
        uses: home-assistant/actions/helpers/version@master

      - name: "Update manifest.json"
        run: |
          python3 ${{ github.workspace }}/.github/scripts/update_hacs_manifest.py --version ${{ steps.version.outputs.version }} --path /custom_components/vector_robot/
      - name: Commit manifest update
        run: |
          if [ $(git diff HEAD | wc -l) -gt 30 ]
          then
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config user.name "GitHub Actions"
          git commit -m "Updated manifest.json" -a || true
          git push || true
      - name: Create zip
        run: |
          cd custom_components/vector_robot
          zip vector_robot.zip -r ./
      - name: Upload zip to release
        uses: svenstaro/upload-release-action@v1-release
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./custom_components/vector_robot/vector_robot.zip
          asset_name: vector_robot.zip
          tag: ${{ github.ref }}
          overwrite: true